version: '3.3'
services:
  rabbit_mq:
    # image: bitnami/rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    # volumes:
      # - ./storage/data/:/var/lib/rabbitmq/
      # - ./storage/logs/:/var/log/rabbitmq
